name: Desafio Certi
on:
  push:
    branches:
      - workflow-branch
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        run: pytest -vv
